name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Commit ID
        id: commit_id
        run: echo "::set-output name=COMMIT_ID::$(git rev-parse HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: luqmankendal54/test-cicd-to-vps:${{ steps.commit_id.outputs.COMMIT_ID }}
