name: cicd

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: luqmankendal54/test-cicd-to-vps-1:latest ,luqmankendal54/test-cicd-to-vps-1:${{ github.sha }}
      # # After you have successfully pushed Docker to Docker Hub, and you know the image ID, then you can continue with the CD steps to your VPS

      # CD steps to your VPS
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            cd ~/deployment/
            docker stop test-cicd-to-vps-1 && docker rm test-cicd-to-vps-1 || true
            docker rmi -f b2384f1ad730 || true
            docker pull luqmankendal54/test-cicd-to-vps-1:${{ github.sha }}
            docker run -d -p 3005:80 --name test-cicd-to-vps-1 luqmankendal54/test-cicd-to-vps-1:${{ github.sha }}
